config/routes.rb
Rails.application.routes.draw do

  resources :pages, :controller => 'pagificate/pages'

end

app/models/pagificate/page.rb
module Pagificate

  class Page < ActiveRecord::Base

    has_permalink :title

    validates :title, :presence => true, :uniqueness => true

    def to_param
      permalink
    end

  end

end

app/controllers/pagificate/pages_controller.rb
module Pagificate

  class PagesController < ApplicationController

    unloadable

    before_filter :find_page, :except => [:index, :new, :create, :show]

    def index
      @published_pages   = Page.where('pages.published = ?', true)
      @unpublished_pages = Page.where('pages.published = ?', false)
    end

    def show
      page = Page.find_by_permalink params[:id]
      page.published? ? @page = page : redirect_to('/', :notice => 'No such page exists')
      render :layout => false unless @page.use_site_layout?
    end

    def new
      @page = Page.new
    end

    def create
      @page = Page.new params[:page]

      respond_to do |format|
        if @page.save
          format.html { redirect_to pages_path, :notice => 'Page created successfully.' }
        else
          flash[:error] = 'Page could not be created.'
          format.html { render :action => :new }
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @page.update_attributes(params[:page])
          format.html { redirect_to pages_path, :notice => 'Page updated.'}
        else
          flash[:error] = 'Page could not be updated.'
          format.html { render :action => :edit }
        end
      end
    end

    def destroy
      @page.destroy

      respond_to do |format|
        format.html { redirect_to pages_path, :notice => 'Page deleted.'}
      end
    end

private

    def find_page
      @page = Page.find_by_permalink params[:id]
    end

  end

end

app/views/pagificate/pages/_form.html.erb
<% if @page.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

    <ul>
    <% @page.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<p>
  <%= f.label :title, 'Title' %><br />
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :body, 'Body' %><br />
  <%= f.text_area :body %>
</p>

<p>
  <%= f.label :published, 'Published' %><br />
  <%= f.check_box :published %>
</p>

<p>
  <%= f.label :use_site_layout, 'Use Site Layout' %><br />
  <%= f.check_box :use_site_layout %>
</p>

<p>
  <%= f.submit 'Save', :disable_with => 'Saving...' %>
</p>

app/views/pagificate/pages/edit.html.erb
<h1>Editing <%= @page.title %></h1>

<%= form_for :page, :url => page_path(@page), :html => { :method => :put } do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end -%>

app/views/pagificate/pages/index.html.erb
<h1>Pages</h1>

<%= link_to 'Add a new page', new_page_path %>

<h2>Published</h2>

<table border="0" cellspacing="5" cellpadding="5">
  
  <thead>
    <tr>
      <th>Title</th>
      <th colspan='2'>&nbsp;</th>
    </tr>
  </thead>
  
  <tbody>
    <% @published_pages.each do |page| %>
      <tr>
        <td><%= link_to page.title, page_path(page) %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Delete', page_path(page), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<h2>Draft</h2>

<table border="0" cellspacing="5" cellpadding="5">
  
  <thead>
    <tr>
      <th>Title</th>
      <th colspan='2'>&nbsp;</th>
    </tr>
  </thead>
  
  <tbody>
    <% @unpublished_pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Delete', page_path(page), :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/pagificate/pages/new.html.erb
<h1>New Page</h1>

<%= form_for :page, :url => pages_path do |f| -%>
  <%= render :partial => 'form', :locals => { :f => f } %>
<% end -%>

app/views/pagificate/pages/show.html.erb
<% content_for :title do %>
  <%= @page.title %>
<% end %>

<%= raw @page.body %>